### PR TITLE
Added multiple exchanges and binding keys when in consumer mode

### PR DESCRIPTION
**Pull request by dihedron**
Ok, so here I am, back with another PR which I hope you'll appreciate.

**ISSUE:**
When in Consumer mode, it should be possible to bind one's queue against multiple exchanges using multiple binding keys. The current implementation only supports one Exchange at a time.

**PROPOSED SOLUTION:**
I'm proposing an extension that addresses this limitation **when in Consumer mode**.
It should now be possible to specify multiple exchanges, each one with its own binding keys, when consuming messages; when in Producer or Both mode the library falls back to the current implementation and expects (and asserts) there is only one exchange in the Options.
The PR addresses this in the simplest way:

1. I moved the ExchangeXXX fields in the Options struct into a separate type (`Binding struct {}`)
2. I added a slice `Bindings []Binding` to the **current** implementation of `Options`
3. When in consumer mode, I loop over the `Bindings`; when in Both and Producer mode I assume there is only one element in the slice (and ensure it is actually so in `ValidateOptions()`);
4. Added all the relevant tests to make sure it is covered by the test suite.

Note: in the process I had to reshuffle some code to make the feature fit more nicely.

I've asked myself whether it would be nicer on your library users to have two separate versions of the `New()` function: the current one, untouched from the client's standpoint:

```golang
type Options struct {
   ExchangeName string
   ...
}

func New(opts *Options) {
   // prepare the new OptionsV2 and then delegate
   optsv2 := OptionsV2 {
       Bindings: []Binding {
           ExchangeName: opts.ExchangeName,
           ....
        },
        ....
    return NewV2(optsv2)
}
```
but changed inside in order to call a brand new one ("v2"):

``` golang
type OptionsV2 struct {
    Bindings []Binding
    ...
}

func NewV2(opts * OptionsV2) {
    // do the real stuff
}
```

Since there are only 29 stars on the repo so far, maybe the API is still to be considered "unstable"; cluttering it with an `OptionsV2` and a `NewV2` right from its early days would be overkill, especially if you consider that v2 is the one that provides the most flexibility with very little overhead. Anyway, modifying the PR to implement it in a backward compatible way would be trivial, so just let me know.

Thanks for your attention, best regards!

### CODE REVIEW

**Comment by dselans** [comment]
Hey there - your PR is definitely appreciated :) 

As for v1 vs v2 and not breaking backwards compat - I agree with you. The library is super young - if we want to change the API, now is the time to do it - so let's not litter it with NewV2, OptionsV2 etc.

I generally really like being able to specify multiple exchanges w/ multiple binds but I think we could go one extra step.

How about we also include a queue name inside the `Binding`? That way you are not limited to having ALL messages arrive in the same queue.

The code looks good and if you have other ideas around the API - let's make it happen.

**Comment by dihedron** [comment]
OK, thanks.
I assume you're definitely more savvy than me when it comes to RabbitMQ; my scenario is much simpler. 
The  `queue -*---*- binding -*---*- exchange` scenario looks more complicated than the one I'm addressing here, and I haven't read enough about RabbitMQ topologies to be 100% sure it's a common pattern. Anyway, I trust you when you say it makes sense and people use it.
I fear the changes would have to be a bit more invasive, though. 
I have to take a look at it when I'm back from work and it might take a while. Nights are never long enough.

**Comment by dselans** [comment]
I don't know if it's a common pattern but it's a pattern we (Batch) often utilize - we have queues that can safely disappear and other queues that have dead letter properties. This would be enable the lib to be *extremely* malleable.

As for what's involved - need to expose existing queue name + properties (auto-declare, auto-del, exclusive) and add "arguments". I don't think this is a big lift. Let me know what you think and if you're OK with doing it.

**Comment by dihedron** [comment]
Your proposal looks extremely versatile but I need your help to clarify how you'd expect the code to flow.

Queues are first involved when declaring and binding, inside `newServerChannel`; the trivial addition would be to simply loop over the queues and do multiple times what is already done for the one queue.

```golang
	if r.Options.Mode == Both || r.Options.Mode == Consumer {
                // something along the lines of
                for _, queue := range r.Bindings {
		  if r.Options.QueueDeclare {
			  if _, err := ch.QueueDeclare(<QUEUE DATA HERE>...); err != nil {
				  return nil, err
			  }
		  }
  
		  for _, bindingKey := range r.Options.BindingKeys {
			  if err := ch.QueueBind(<QUEUE DATA HERE>...); err != nil {
				  return nil, errors.Wrap(err, "unable to bind queue")
			  }
		  }
             }
	}
```
But then comes the hard stuff: when you actually start to `Consume()` messages from the `amqp.Channel` you have to **specify again the name of the queue**, and it seems to me you receive a single `amqp.Delivery` for every queue:

```golang
deliveryChannel, err := serverChannel.Consume(
		r.Options.QueueName,
		r.Options.ConsumerTag,
		r.Options.AutoAck,
		r.Options.QueueExclusive,
		false,
		false,
		nil,
	)
```

From a cursory look at streadway/amqp docs, I don't see any hint about why `Consume()` requires a `queueName`, but I presume it's because they maintain an `amqp.Delivery` per queue, so you end up with as many `amqp.Delivery`es as you have added queues to the Bindings.

In the end things get quite complicated: you don't have a single channel: you have one for each queue instead. 

What do we do? Do we return a slice of channels and leave it up to the caller to do what they can with those channels? Or do we `select` and then de-mux into a single channel maintained by us?

And then, each queue could be exclusive, persistent, autodeclare....

I'll be honest, this thing seems more like it would best managed by the caller: you need to consume from multiple queues? You excplicitly open multiple clients, get you `amqp.Delivery`es, then decide what to do with each channel, `select` or whatever.

My 2 cents.

**Comment by dselans** [comment]
Thanks for doing the research. I forgot that `.Consume(..)` expects a queue name. The implementation would be a bit more complex - we'd need to keep track of all server channels and consume on them in parallel and as you suggested, probably push all the delivery messages to a central channel owned by us.

Your suggestion of doing this on the caller side is exactly how we've dealt with it now - we have a wrapper for this library, that allows us to have several clients. My line of thinking was that if this lib supported the "multi-bind/multi-queue" functionality, then we could significantly reduce the size of our wrapper lib - but it's pretty clear now that it's a fairly significant amount of work.

Let's roll with your current PR and I could post our current wrapper as an example to handle multiple clients.

**Review by dselans — APPROVED** [review]

**Comment by dselans** [comment]
Thanks for your work @dihedron !

**Comment by dihedron** [comment]
My pleasure, @dselans !

**Pull request merged**
