### PR TITLE
Replace logrus with generic Logger

### PR DESCRIPTION
**Pull request by dihedron**
This PR relates to #13 . Please check out if it works for you.

Cheers

### CODE REVIEW

**Comment by dselans** [comment]
Awesome! Will review later today!

**Comment by dselans** [comment]
Hey there - looks good but it sucks having to remember to `if logger != nil` everywhere.

Since we already do ValidateOptions - let's assign a NoOp logger to log if the passed in logger is nil. Our NoOp logger would just do nothing.

**Comment by dihedron** [comment]
Makes perfect sense.

**Comment by dihedron** [comment]
@dselans : done!

**Review by dselans — APPROVED** [review]
Beautiful!

**Pull request merged**
